services:
    dblocations:
        image: postgres
        container_name: dblocations
        restart: always
        user: postgres
        secrets:
            - db-password
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file:
            - .env
        expose:
            - 5432
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10
        networks:
            - net
    
    dbflows:
        image: neo4j:latest
        container_name: dbflows
        restart: on-failure
        ports:
            - 7474:7474
            - 7687:7687
        env_file:
            - .env
        volumes:
            - neo4j_data:/data
            - neo4j_logs:/logs
            - neo4j_import:/var/lib/neo4j/import
            - neo4j_plugins:/plugins
        networks:
            - net
        healthcheck:
            test: wget http://localhost:7474 || exit 1
            interval: 1s
            timeout: 5s
            retries: 20
            start_period: 90s
     
    webapp:
        build: ./nta_app
        container_name: webapp
        ports: 
            - 8889:8080
        env_file:
            - .env
        depends_on:
            dblocations:
                condition: service_healthy
            dbflows:
                condition: service_healthy
        networks:
            - net
        secrets:
            - db-password
        volumes:
            - /tmp/.X11-unix/:/tmp/.X11-unix/
            - neo4j_import:/app/db_insert

networks:
    net:
        driver: bridge

volumes:
    db-data:
    pgadmin-data:
    neo4j_data:
    neo4j_logs:
    neo4j_import:
    neo4j_plugins:
    
secrets:
    db-password:
        file: nta_app/password.txt